spring:
  application:
    name: lab-09-springmvc-vs-webflux

  # WebFlux 配置
  webflux:
    # 基础路径
    base-path: /
    # 默认格式化程序
    format:
      date: yyyy-MM-dd
      time: HH:mm:ss
      date-time: yyyy-MM-dd HH:mm:ss

  # Jackson 配置
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /
  # 超时设置
  shutdown: graceful
  shutdown-wait-time: 30s

# 日志配置
logging:
  level:
    root: INFO
    nan.tech: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 管理端点 (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

# 自定义配置
app:
  name: Lab-09 Spring WebFlux
  version: 1.0.0-SNAPSHOT
  author: Claude Code + Compounding Engineering
